---
# tasks file for ansible-flannel
- name: Create systemd drop-in directory
  file: path={{flanneld_dropin_dir}} state=directory mode=0755
  sudo: yes
  sudo_user: root

- name: Set flannel options
  sudo: yes
  template: src=options.env.j2 dest={{flannel_options_env}} mode=0644
  notify: reload systemd

- name: Set peers conf
  sudo: yes
  template: src=50-network-config.conf dest={{flanneld_dropin_dir}}/50-network-config.conf
  notify: reload systemd

- name: Add flanneld-install unit
  sudo: yes
  template: src=flanneld-install.service dest=/etc/systemd/system/flanneld-install.service
  notify: reload systemd
